export const blogs = [
    // Add more blog data here
    {
        id: 49,
        title: "Fusion of Modern Cardiac care with Ancient Prana Healing",
        date: "8 November 2024",
        image: "/blog-8-11-2024.jpeg",
        description: "https://www.youtube.com/live/3JjzX3TCCPc",
        link: "/blog/fusion-of-modern-cardiac-care-with-ancient-prana-healing",
    },
    {
        id: 48,
        title: "A CASE OF PERCEIVED BLACK MAGIC ATTACK HEALED USING YPV PROTOCOLS",
        date: "17 October 2024",
        image: "/images/healthy-mindset.jpg",
        description: "Article link : https://doi.org/10.29121/granthaalayah.v12.i9.2024.5798",
        link: "/blog/a-case-of-perceived-black-magic-attack-healed-using-ypv-protocols",
    },
    {
        id: 47,
        title: "Healing camp at satkhol, Uttarakhand",
        date: "1 June 2024",
        image: "/blog-1-06-2024.jpeg",
        description: "",
        link: "/blog/healing-camp-at-satkhol-uttarakhand",
    },
    {
        id: 46,
        title: "Impact of the Great Invocation Practice at Vellalar College",
        date: "21 May 2024",
        image: "",
        description: "Issue link : https://www.ijfmr.com/research-paper.php?id=15210",
        link: "/blog/impact-of-the-great-invocation-practice-at-vellalar-college",
    },
    {
        id: 45,
        title: "Interpretative Analysis of the Experiences of Women YPV Healers",
        date: "5 April 2024",
        image: "/blog-5-04-2024.webp",
        description: "Exploring the Psycho-Social Issues in the Life Journey to Becoming a Healer: An Interpretative Phenomenological Analysis of the Experiences of Women Yoga Prana Vidya (YPV) Healers in the Indian Context<br/>Issue link : https://ijip.in/issue/?volumes=Volume-12-Issue-1",
        link: "/blog/interpretative-analysis-of-the-experiences-of-women-ypv-healers",
    },
    {
        id: 44,
        title: "Pediatric patient case of vesicoureteral reflux healed using YPV",
        date: "22 January 2024",
        image: "/blog-22-01-2024.webp",
        description: "Article link: https://mansapublishers.com/index.php/ijch/article/view/4339",
        link: "/blog/pediatric-patient-case-of-vesicoureteral-reflux-healed-using-ypv",
    },
    {
        id: 43,
        title: "TRIGEMINAL NEURALGIA: A CASE OF SUCCESSFUL TREATMENT USING YPV",
        date: "8 December 2023",
        image: "/blog-8-12-2023.webp",
        description: "Issue link: http://www.wjahr.com/home/current_issues",
        link: "/blog/trigeminal-neuralgia-a-case-of-successful-treatment-using-ypv",
    },
    {
        id: 42,
        title: "Managing Fatigue and Improving Happiness using YPV Energy Healing",
        date: "20 November 2023",
        image: "/blog-20-11-2023.jpeg",
        description: " Facebook <br/> 📸 Watch this live video on Facebook https://fb.watch/opUx3H5fSc/?mibextid=ZbWKwL  <br/> Youtube link  https://www.youtube.com/live/Arxah4dUb8k?si=xM2x7WFA0sYXYsDZ",
        link: "/blog/managing-fatigue-and-improving-happiness-using-ypv-energy-healing",
    },
    {
        id: 41,
        title: "ESOPHAGEAL VARICES AND POST-EVL COMPLICATIONS CASE USING YPV",
        date: "26 October 2023",
        image: "/blog-26-10-2023.webp",
        description: "Article link: https://www.ijoimr.com/index.php/ijoimr/article/view/ijoimr134",
        link: "/blog/esophageal-varices-and-post-evl-complications-case-using-ypv",
    },
    {
        id: 40,
        title: "Treating Ovarian Cysts with YPV Energy Healings",
        date: "26 October 2023",
        image: "/blog-26-10-2023-1.jpeg",
        description: "Facebook Link <br/> https://fb.watch/nQZmxvhq8J/?mibextid=ZbWKwL <br/> Youtube link <br/> https://www.youtube.com/live/76ulRLpYuU4?si=I8SbtOV7-4oxECVb",
        link: "/blog/treating-ovarian-cysts-with-ypv-energy-healings",
    },
    {
        id: 39,
        title: "YPV Energy Healings help in Overcoming Addictions",
        date: "8 October 2023",
        image: "/blog-8-10-2023.jpeg",
        description: "Youtube link <br/> https://www.youtube.com/live/s0DaAyubivc?si=45Y4g7e7Cz-5KjbZ <br/> Facebook Link <br/> https://fb.watch/nyxaTDziOT/?mibextid=ZbWKwL",
        link: "/blog/ypv-energy-healings-help-in-overcoming-addictions",
    },
    {
        id: 38,
        title: "Recovering from Adenomyosis through YPV Energy Healing",
        date: "26 September 2023",
        image: "/blog-26-09-2023.jpeg",
        description: "Facebook Link <br/> https://fb.watch/nhooiklCd8/?mibextid=Nif5oz <br/> Youtube link <br/> https://www.youtube.com/live/h238Ryw_3zc?si=cXApZCjZoT5ZqoxH",
        link: "/blog/recovering-from-adenomyosis-through-ypv-energy-healing",
    },
    {
        id: 37,
        title: "YPV Healings help in recovering from Metastatic Breast Cancer",
        date: "10 September 2023",
        image: "/blog-10-09-2023.jpeg",
        description: "Youtube <br/> https://www.youtube.com/live/nflpwRnvN18?si=3IRmcmg2cHehM6EF <br/> Facebook <br/> https://fb.watch/mZCcm3ANMH/?mibextid=CDWPTG",
        link: "/blog/ypv-healings-help-in-recovering-from-metastatic-breast-cancer",
    },
    {
        id: 36,
        title: "Treating Symptoms of PCOS with YPV Energy Healings",
        date: "4 September 2023",
        image: "/blog-4-09-2023.jpeg",
        description: "Facebook Link <br/> https://fb.watch/mQnrw6QMbv/?mibextid=CDWPTG <br/> Youtube link <br/> https://www.youtube.com/live/lGmG9Y0IuVY?si=7_h0jEoeA9n6YlP2",
        link: "/blog/treating-symptoms-of-pcos-with-ypv-energy-healings",
    },
    {
        id: 35,
        title: "A Pediatric Bronchopneumonia case healed using Yoga Prana Vidya",
        date: "15 August 2023",
        image: "/blog-15-08-2023.jpeg",
        description: "Facebook - https://www.facebook.com/YogaPranaVidya.YPV/videos/1719397111859441/?mibextid=NnVzG8 <br/> YouTube - https://www.youtube.com/live/SaFcaMa1Io4?feature=share",
        link: "/blog/a-pediatric-bronchopneumonia-case-healed-using-yoga-prana-vidya",
    },
    {
        id: 34,
        title: "Ringworm Infection: A case of successful cure using YPV protocols",
        date: "29 July 2023",
        image: "/blog-29-07-2023.jpg",
        description: "Article link: https://ijmsdr.org/published%20paper/1i1i29/",
        link: "/blog/ringworm-infection-a-case-of-successful-cure-using-ypv-protocols",
    },
    {
        id: 33,
        title: "YPV Energy Healings help in Increasing Viability of IVF",
        date: "18 July 2023",
        image: "/blog-18-07-2023.jpeg",
        description: "Facebook <br/> https://fb.watch/lPN0LFnaGX/?mibextid=ZbWKwL <br/> Youtube <br/> https://www.youtube.com/live/MG0eV1ld414?feature=share",
        link: "/blog/ypv-energy-healings-help-in-increasing-viability-of-ivf",
    },
    {
        id: 32,
        title: "A case of chocolate ovarian cyst successfully healed using YPV",
        date: "7 July 2023",
        image: "/blog-7-07-2023.jpg",
        description: "Article link: https://www.wjpls.org/home/article_abstract/3013",
        link: "/blog/a-case-of-chocolate-ovarian-cyst-successfully-healed-using-ypv",
    },
    {
        id: 31,
        title: "Case of diabetic retinopathy with blurred vision healed using YPV",
        date: "6 July 2023",
        image: "/blog-6-07-2023.jpg",
        description: "Article link: https://www.ijceo.org/article-details/19156 <br/> Issue link: https://www.ijceo.org/",
        link: "/blog/case-of-diabetic-retinopathy-with-blurred-vision-healed-using-ypv",
    },
    {
        id: 30,
        title: "A case of a female patient having multiple issues healed",
        date: "27 June 2023",
        image: "/blog-27-06-2023.jpg",
        description: "Article link: https://www.ijmacr.com/issue/archive_issue/34",
        link: "/blog/a-case-of-a-female-patient-having-multiple-issues-healed",
    },
    {
        id: 29,
        title: "EXPLORING MANIFESTATION THEORY AND ITS CONNECTION WITH PSYCHOLOGY",
        date: "24 June 2023",
        image: "",
        description: "Article link: http://ijramr.com/issue/exploring-manifestation-theory-and-its-connection-psychology-analysis-results-yoga-prana-vidya",
        link: "/blog/exploring-manifestation-theory-and-its-connection-with-psychology",
    },
    {
        id: 28,
        title: "Successful Healing Treatment of Renal Calculi using YPV protocols",
        date: "24 June 2023",
        image: "/blog-24-06-2023-1.jpg",
        description: "Article link: https://www.informaticsjournals.com/index.php/jnr/article/view/32066",
        link: "/blog/successful-healing-treatment-of-renal-calculi-using-ypv-protocols",
    },
    {
        id: 27,
        title: "Case of Unilateral multicystic dysplastic Kidney headed using YPV",
        date: "24 June 2023",
        image: "/blog-24-06-2023-2.jpg",
        description: "Article link: https://www.ijmacr.com/asset/images/uploads/16806991276528.pdf",
        link: "/blog/case-of-unilateral-multicystic-dysplastic-kidney-headed-using-ypv",
    },
    {
        id: 26,
        title: "Recovering from Irritable Bowel Syndrome with YPV Energy Healings",
        date: "18 June 2023",
        image: "/blog-18-06-2023.jpeg",
        description: "Research paper Bookstudy link <br/> https://fb.watch/leSBxys5_l/?mibextid=ZbWKwL <br/> Youtube link <br/> https://www.youtube.com/live/ASdCUkWbjlU?feature=share",
        link: "/blog/recovering-from-irritable-bowel-syndrome-with-ypv-energy-healings",
    },
    {
        id: 25,
        title: "Patient Having PCOD Healed Successfully Using YPV protocols",
        date: "31 May 2023",
        image: "/blog-31-05-2023.jpg",
        description: "Article link: https://doi.org/10.58806/ijhmr.2023.v2i5n03 <br/> Pdf link: https://ijhmr.com/wp-content/uploads/2023/05/3.pdf",
        link: "/blog/patient-having-pcod-healed-successfully-using-ypv-protocols",
    },
    {
        id: 24,
        title: "Skin Allergy and Injury healed using YPV protocols",
        date: "31 May 2023",
        image: "/blog-31-05-2023-1.jpg",
        description: "Link to the issue of journal: https://www.ijmsdr.org/pages/Current%20Issue.html <br/> Article link: https://www.ijmsdr.org/published%20paper/1i1i28/Skin-Allergy-and-Injury-A-Case-Series-Study-of-Successful-Healing-Using-Yoga-Prana-Vidya-(YPV)-Healing-Protocols.pdf",
        link: "/blog/skin-allergy-and-injury-healed-using-ypv-protocols",
    },
    {
        id: 23,
        title: "Recovering from Vitiligo through YPV techniques",
        date: "26 May 2023",
        image: "/blog-26-05-2023.jpeg",
        description: "YouTube link <br/> https://www.youtube.com/live/G7xM3sjaqEY?feature=share <br/> Facebook Link <br/> https://fb.watch/kMh5EULfJo/?mibextid=qC1gEa",
        link: "/blog/recovering-from-vitiligo-through-ypv-techniques",
    },
    {
        id: 22,
        title: "YPV protocols to overcome Trauma and Side Effects of Cancer",
        date: "26 May 2023",
        image: "/blog-26-05-2023-1.jpg",
        description: "https://www.yogapranavidya.com/wp-content/uploads/2023/05/YPV-research-77th-published-article-Experiences-of-a-50-year-old-Breast-Cancer-Survivor_-Role-of-Yoga-Prana-Vidya-Protocols-as-Complementary-Therapy-06-05-2023-3.pdf",
        link: "/blog/ypv-protocols-to-overcome-trauma-and-side-effects-of-cancer",
    },
    {
        id: 21,
        title: "YPV protocols to overcome Addiction and Empower Rehabilitation",
        date: "26 May 2023",
        image: "/blog-26-05-2023-2.jpg",
        description: "https://juniperpublishers.com/gjarm/pdf/GJARM.MS.ID.555704.pdf",
        link: "/blog/ypv-protocols-to-overcome-addiction-and-empower-rehabilitation",
    },
    {
        id: 20,
        title: "YPV Healings help recover from Auto-Immune diseases",
        date: "9 May 2023",
        image: "/blog-9-05-2023.jpeg",
        description: "https://www.youtube.com/live/kHzZDgs-qRo?feature=share",
        link: "/blog/ypv-healings-help-recover-from-auto-immune-diseases",
    },
    {
        id: 19,
        title: "A case of deep vein thrombosis healed successfully using YPV",
        date: "2 May 2023",
        image: "/blog-2-05-2023.webp",
        description: "Article link: <br/> https://zealjournals.com/wjapmr/content/case-deep-vein-thrombosis-42-years-old-male-patient-healed-successfully-using-yoga-prana",
        link: "/blog/a-case-of-deep-vein-thrombosis-healed-successfully-using-ypv",
    },
    {
        id: 18,
        title: "Recovering from Brain surgery and post surgery complications",
        date: "3 April 2023",
        image: "/blog-3-04-2023.webp",
        description: "Link to attend Research paper Bookstudy <br/> Youtube <br/> https://www.youtube.com/live/uSJ3t6B2qak?feature=share <br/> Facebook <br/> https://www.facebook.com/YogaPranaVidya.YPV/videos/616981206516246/?sfnsn=wiwspmo&mibextid=VhDh1V",
        link: "/blog/recovering-from-brain-surgery-and-post-surgery-complications",
    },
    {
        id: 17,
        title: "Full Recovery from PCOS without medication using YPV Healing",
        date: "24 March 2023",
        image: "/blog-24-03-2023.jpeg",
        description: "Fb - https://fb.watch/jtdR00hE27/ <br/> YouTube - https://www.youtube.com/live/pFz9F_bsaK8?feature=share",
        link: "/blog/full-recovery-from-pcos-without-medication",
    },
    {
        id: 16,
        title: "Fetal heart rate and potential birth defects healed using YPV",
        date: "4 March 2023",
        image: "/blog-4-03-2023.webp",
        description: "Article link: <br/> https://ijmsdr.org/pages/Current%20Issue.html",
        link: "/blog/fetal-heart-rate-and-potential-birth-defects-healed-using-ypv",
    },
    {
        id: 15,
        title: "Adnexal mass with malignant cells healed successfully using YPV",
        date: "4 March 2023",
        image: "/blog-4-03-2023-1.webp",
        description: "Article link: <br/> https://innovativejournal.in/index.php/ijmhs/issue/view/708",
        link: "/blog/adnexal-mass-with-malignant-cells-healed-successfully-using-yoga",
    },
    {
        id: 14,
        title: "YPV Energy Healing for dislocated joints",
        date: "23 January 2023",
        image: "/blog-23-01-2023.jpeg",
        description: "Research book study <br/> Facebook - https://www.facebook.com/watch/?v=554494476736051 <br/> YouTube - https://youtu.be/lkz7xOUlEvM",
        link: "/blog/ypv-energy-healing-for-dislocated-joints",
    },
    {
        id: 13,
        title: "A case of vasculitic neuropathy successfully healed using YPV",
        date: "29 December 2022",
        image: "/blog-29-12-2022.webp",
        description: "Publications: World Journal of Biology Pharmacy and Health Sciences <br/> Article link: <br/> https://wjbphs.com/content/case-vasculitic-neuropathy-successful-healing-using-yoga-prana-vidya-ypv-healing-protocols",
        link: "/blog/a-case-of-vasculitic-neuropathy-successful-healed-using-ypv",
    },
    {
        id: 12,
        title: "Yoga Prana Vidya Distance healings for Covid-19 patients",
        date: "25 December 2022",
        image: "/blog-25-12-2022.webp",
        description: "https://www.yogapranavidya.com/about-ypv-research/publications/yoga-prana-vidya-distance-healing-intervention-for-covid-19-patients-an-outcome-case-study/",
        link: "/blog/yoga-prana-vidya-distance-healings-for-covid-19-patients",
    },
    {
        id: 11,
        title: "A case of stage 2 kidney disease successfully treated using YPV",
        date: "17 December 2022",
        image: "/blog-17-12-2022.webp",
        description: "https://drive.google.com/file/d/1rgJJB6S6-24-Yrwdnbl7fI6cyKPhmy1I/view?usp=share_link",
        link: "/blog/a-case-of-stage-2-kidney-disease-successfully-treated-using-ypv",
    },
    {
        id: 10,
        title: "Burn case successfully treated using YPV",
        date: "17 December 2022",
        image: "/blog-17-12-2022-1.jpeg",
        description: "https://drive.google.com/file/d/1M-ZYMERPaS4a9FBTaLrIH1beDnHV1CpC/view?usp=share_link",
        link: "/blog/burn-case-successfully-treated-using-ypv",
    },
    {
        id: 9,
        title: "A case of Discoid Lupus healed successfully using YPV",
        date: "17 December 2022",
        image: "/blog-17-12-2022-2.jpeg",
        description: "https://drive.google.com/file/d/1RIxn1Op4efjafVKukAcZhfiDFo1x-gld/view?usp=share_link",
        link: "/blog/a-case-of-discoid-lupus-healed-successfully-using-ypv",
    },
    {
        id: 8,
        title: "Role of YPV System Protocols in Infertility Treatment",
        date: "13 December 2022",
        image: "/blog-13-12-2022.jpeg",
        description: "http://ijpbms.com/index.php/ijpbms/article/view/155",
        link: "/blog/role-of-ypv-system-protocols-in-infertility-treatment",
    },
    {
        id: 7,
        title: "A case of Esophageal cancer stage 2 successfully healed using YPV",
        date: "12 December 2022",
        image: "/blog-12-12-2022.jpeg",
        description: "https://innovativejournal.in/index.php/ijmhs/article/view/3475/3051",
        link: "/blog/a-case-of-esophageal-cancer-stage-2-successfully-healed-using-ypv",
    },
    {
        id: 6,
        title: "A Case Study of Senso Neural Hearing Loss healed successfully",
        date: "11 December 2022",
        image: "/blog-11-12-2022.jpeg",
        description: "Publications: INTERNATIONAL JOURNAL OF PHARMACEUTICAL AND BIO-MEDICAL SCIENCE <br/> Article link: <br/> http://ijpbms.com/index.php/ijpbms/article/view/203",
        link: "/blog/a-case-study-of-senso-neural-hearing-loss-healed-successfully",
    },
    {
        id: 5,
        title: "PostCovid Complications of Asthma",
        date: "26 November 2022",
        image: "/blog-26-11-2022.jpg",
        description: "https://youtu.be/xImem-JIY-E <br/> https://youtu.be/ZMYr4C_VEiM",
        link: "/blog/postcovid-complications-of-asthma",
    },
    {
        id: 4,
        title: "YPV Healings help in reversing the impact of Diabetes",
        date: "28 October 2022",
        image: "/blog-28-10-2022.webp",
        description: "Talk on the impact of Energy Healing on patients of Diabetes published in the journal of Biology and Life Sciences. <br/> https://youtu.be/F8PyYFOZWPc",
        link: "/blog/ypv-healings-help-in-reversing-the-impact-of-diabetes",
    },
    {
        id: 3,
        title: "YPV Healing treatment of a 48 year old male with Heart blockage",
        date: "28 October 2022",
        image: "/blog-28-10-2022-1.webp",
        description: "Research paper presentation of a 48 year old male with Heart blockage successfully treated with Yoga Prana Vidya Healing. <br/> https://youtu.be/XZraLhDvawQ",
        link: "/blog/ypv-healing-treatment-of-a-48-year-old-male-with-heart-blockage",
    },
    {
        id: 2,
        title: "Energy Healing a cure for seasonal Dengue",
        date: "21 October 2022",
        image: "/blog-21-10-2022.jpg",
        description: "Dengue can be considered as a viral disease with rapid declining of blood platelets. <br/> If with immune system building viral load can be eliminated fast then this decline can be reversed. <br/> Platelets going down beyond 50000 can be severe for patient. <br/> We have seen that just within 1 to 3 days of hospitalized patient healing .....there is marked improvement in external conditions and internal parameters including  appetite, liver condition, fever, abdominal pain condition, rashes and finally platelets reversal. <br/> Though at least 15 days healing is recommended to bring patient condition to normal with platelets count more than 1.5 to 4.5 lac. <br/> Energy healing specially yoga prana vidya is a great help when used with modern allopathy in integration.",
        link: "/blog/energy-healing-a-cure-for-seasonal-dengue",
    },
    {
        id: 1,
        title: "SCANNING CHEMICAL ENERGIES",
        date: "11 October 2022",
        image: "/blog-11-10-2022.jpg",
        description: "Mangoes, bananas are the most delicious of fruits but are often  ripened artificially by Chemical treatment thereby impregnating it with chemical energy which cannot be removed by water or other treatment. <br/> Already many harmful chemicals are sprayed on these fruit plants during its cultivation practices. <br/> Special attention should be given to obtain artificial ripening free fruits. <br/> Gastro intestinal diseases are often most common in masses due to indescrminate use of chemicals in fruits and vegetables. <br/> Organic fruits and vegetables are often available in every city but should be scanned to ascertain their authenticity. <br/> Our aura vibrations often matches with plants vibrational  frequency but chemical  contamination of plant kingdom often hinders these property. <br/> As one cannot go for chemical test for each and every commodity so learning energy scanning is most suitable way to find right eatables for daily use. <br/> This ability can be learned by attending just one day energy scanning workshop at a YPV Centre.",
        link: "/blog/scanning-chemical-energies",
    },
];